/* This file was generated by syncqt. */
#ifndef QT_ACTIVEQT_VERSION_H
#define QT_ACTIVEQT_VERSION_H

#define ACTIVEQT_VERSION_STR "5.4.0"

#define ACTIVEQT_VERSION 0x050400

#endif // QT_ACTIVEQT_VERSION_H
