/* This file was generated by syncqt. */
#ifndef QT_QTOPENGL_VERSION_H
#define QT_QTOPENGL_VERSION_H

#define QTOPENGL_VERSION_STR "5.3.2"

#define QTOPENGL_VERSION 0x050302

#endif // QT_QTOPENGL_VERSION_H
