/* This file was generated by syncqt. */
#ifndef QT_QTUITOOLS_VERSION_H
#define QT_QTUITOOLS_VERSION_H

#define QTUITOOLS_VERSION_STR "5.4.0"

#define QTUITOOLS_VERSION 0x050400

#endif // QT_QTUITOOLS_VERSION_H
