/* This file was generated by syncqt. */
#ifndef QT_QTLOCATION_VERSION_H
#define QT_QTLOCATION_VERSION_H

#define QTLOCATION_VERSION_STR "5.3.2"

#define QTLOCATION_VERSION 0x050302

#endif // QT_QTLOCATION_VERSION_H
